### ISSUE TITLE
Add hidden option to link GEOSgcm.x

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GEOSgcm_App#114]
Per a thought by @bena-nasa it might be nice for us in the SI Team to have a "hidden" option (like `--nocvs` in the old days) where instead of `GEOSgcm.x` being copied into the experiment, it is symlinked. Since we build the model over and over, a symlink'd `GEOSgcm.x` can save us time.

**Comment by sdrabenh** [comment]
@mathomp4 I'm not sure I completely understand the benefits of sym linking an executable. I' also not familiar with the --nocvs option either. Maybe we should chat.

**Comment by mathomp4** [comment]
@sdrabenh Well, back in the days when `gcm_setup` would commit to CVS if it saw differences, I added a `--nocvs` option that would stop that. As the SI Team changes files all the time and runs experiments, we'd have polluted CVS with zillions of branches.

The thought here is similar. When @bena-nasa, @atrayano, or myself make an experiment, the next thing we do is remove the `GEOSgcm.x` from the experiment and then symlink in the one in `$ESMADIR/install/bin`. That way, we can change code, recompile, reinstall, and then go back to our experiment and not need to then do `cp $ESMADIR/install/bin/GEOSgcm.x .`. Instead, we'd always have the "latest" version of `GEOSgcm.x` in our experiment directory.
