### ISSUE TITLE
Open MPI restart performance is dreadful by default

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GEOSgcm_App#116]
Per testing at just C24, with MAPL 2.1 and Open MPI (at least with GCC). By default, you get:
```
--Finalize                                             1   139.592  64.64     0.002   0.00
----GCM                                                1   139.582  64.64     0.003   0.00
------AGCM                                             1   137.837  63.83     0.004   0.00
```
If you use `WRITE_RESTART_BY_OSERVER: YES`, you get:
```
--Finalize                                             1    17.063  15.74     0.012   0.01
----GCM                                                1    17.043  15.72     0.004   0.00
------AGCM                                             1    14.711  13.57     0.004   0.00
```

Probably best to add an "if OpenMPI, turn on in AGCM.rc" fix. Needs testing at NAS to see if this is similar slow between HPC-X and MPT.

**Comment by tclune** [comment]
Oh wow.   Weiyuan did something really good with that.  I'd assumed it was marginal.   Or is the cost just hidden elsewhere?

**Comment by mathomp4** [comment]
I think it's just because the MPI_GatherV with Open MPI on at least the Skylakes is so bad, using that flag changes to use isend/recv or something which is much better.

**Comment by mathomp4** [comment]
Let me do some Intel MPI tests really quick...

**Comment by mathomp4** [comment]
On Intel, default:
```
--Finalize                                             1     6.737   7.98     0.003   0.00
----GCM                                                1     6.722   7.96     0.002   0.00
------AGCM                                             1     6.636   7.86     0.001   0.00
```
with the flag to yes:
```
--Finalize                                             1    10.976  14.35     0.008   0.01
----GCM                                                1    10.959  14.33     0.001   0.00
------AGCM                                             1    10.404  13.60     0.001   0.00
```
So, yeah. 

Note that in both of these, I am not running a "separate" oserver. It's the default "on-the-same-nodes" oserver.
