### ISSUE TITLE
Which S2S History is "correct"?

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GEOSgcm_App#122]
With my adventures getting #121 working, I noticed something. Well a couple things. First, most of the HISTORY template files use an underscore not a dot. But even more exciting is we have *two* S2S HISTORY templates:
```
HISTORY_S2S.rc.tmpl
HISTORY.S2S.rc.tmpl
```
and they seem to be different.

So my question for the @GEOS-ESM/ocean-team is: are they both valid? Should one be removed? I just want to make sure we don't confuse people.

**Comment by mathomp4** [comment]
I've "assigned" @yvikhlya just because he might know the answer...or who to ping for the answer.

**Comment by yvikhlya** [comment]
@mathomp4 One is definitely wrong. I'll ask S2S team which one do we need.

**Comment by yvikhlya** [comment]
@mathomp4 Matt, it looks like HISTORY_S2S.rc.tmpl is used by S2Sv2, and I was told that history for v3 is not set yet.

**Comment by mathomp4** [comment]
@yvikhlya Should I/you/we remove one of these? Since we have a new release of App coming soon?

**Comment by yvikhlya** [comment]
@mathomp4 Submitted PR  #144.

**Comment by mathomp4** [comment]
@yvikhlya Thanks!
