### ISSUE TITLE
Longer coupled run crashes

### ISSUE THREAD

**Issue by sanAkel** [GEOS-ESM/GEOSgcm_App#132]
Need to re-submit gcm_run.j and gcm_post.j manually all the time, because when they are submitted from slurm job, both crash with error: "can't load shared library libiomp5.so" **this needs immediate attention** 

This issue also references following PR:
https://github.com/GEOS-ESM/GEOSgcm_App/pull/113

**Comment by tclune** [comment]
Some layer needs a find_package(OpenMP)

**Comment by mathomp4** [comment]
@sanAkel If you'd like us to test this, we'd need to know what to clone, checkout, etc. and how to setup an experiment and run as well.

**Comment by yvikhlya** [comment]
@mathomp4 Instructions on how to build MOM5+MOM6 model:
https://github.com/GEOS-ESM/GEOSgcm/blob/feature/yury/mom6/README_mom6.md

Experiment which fails to re-submit:
~yvikhlia/geos5/v10_12_4-mom6
~yvikhlia/aogcm/v10_12_4-mom6

**Comment by mathomp4** [comment]
@yvikhlya I'll try a clone, but if not, I'll need you to tell me what to answer in `gcm_setup` (though it looks like MOM6 does pretty much nothing).

**Comment by yvikhlya** [comment]
@mathomp4 You can use gcm_setup and choose mom5 with all defaults. It does not re-submit either.

**Comment by yvikhlya** [comment]
This issue is resolved and can be closed I guess?

**Comment by sanAkel** [comment]
As for my runs with either MOM5 or MOM6, 

- For some reason (don't know it!) I do not need to set LD_LIBRARY_PATH to include ${GEOSDIR}/lib In fact when I had it, the run with MOM6 crashed with an error: `./GEOSgcm.x: symbol lookup error: ./GEOSgcm.x: undefined symbol: __libm_logf_table_256` Following suggestion from @mathomp4 dropping ${GEOSDIR}/lib it didn't crash and went through, resubmitted itself. 
- I did need to set LD_PRELOAD, just as @yvikhlya says he does:
  + env LD_PRELOAD=$GEOSDIR/lib/libmom6.so $RUN_CMD GEOSgcm.x for MOM6 
  + env LD_PRELOAD=$GEOSDIR/lib/libmom.so   $RUN_CMD GEOSgcm.x for MOM5

Just with above, my runs have successfully resubmitted themselves

**Comment by sanAkel** [comment]
Once updated to: https://github.com/GEOS-ESM/GEOSgcm_App/tree/final-stress-rebase-with-develop-2020Jun16
this issue is resolved.

**Comment by sanAkel** [comment]
PR https://github.com/GEOS-ESM/GEOSgcm/pull/172 includes it.

**Comment by sanAkel** [comment]
updated to: https://github.com/GEOS-ESM/GEOSgcm_App/pull/140

**Comment by sanAkel** [comment]
https://github.com/GEOS-ESM/GEOSgcm/pull/172 --> closing this issue.
