### ISSUE TITLE
Check for openwater_internal_restart and then invoke following logic...

### ISSUE THREAD

**Issue by sanAkel** [GEOS-ESM/GEOSgcm_App#161]
https://github.com/GEOS-ESM/GEOSgcm_App/blob/develop/gcm_run.j#L668-L699

**Comment by sanAkel** [comment]
Long runs inadvertently pick up saltwater_internal_rst if it exists for the first segment. 

We should really invoke this logic if there **does not** exist openwater internal **and** seaicethermo_intenal

**Comment by zhaobin74** [comment]
In addition,  I'd recommend deleting saltwater_internal_rst after the splitting is done, just to make things explicit. saltwater_internal_rst becomes redundant anyway.
