### ISSUE TITLE
Loosen Job Name Length Requirements in GCM

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GEOSgcm_App#164]
This is a question for @lltakacs, @sdrabenh, and @yvikhlya (and maybe @mmanyin and @christophkeller as the Chem Post world is magic to me) as it mainly concerns postprocessing. I was wondering if you believe there is any need to still cut down job names:
https://github.com/GEOS-ESM/GEOSgcm_App/blob/b4a274f71e65ec70ab10952a705c0a9b15726bb3/gcm_setup#L1261-L1268
I know SLURM can handle longer than that as can the PBS now at NAS. (I'm asking NCCS and NAS to see if there is a limit still, but just a longer one.) It might be nice to have longer job names so looking on squeue, etc is more useful.

But what I don't know is whether the postprocessing looks for the slurm job name for anything and thus is expecting a 16-character string.

Obviously I might try a year-long C24 run with a stupid long expid and see what happens, but I figured I'd ask first.

**Comment by yvikhlya** [comment]
@mathomp4 I never cared about job name length and they always get cut. Not sure how does this matter for post processing.

**Comment by mmanyin** [comment]
I am not aware of any chem-specific limitations in this regard; if PBS and SLURM can handle longer names, I think it would be a good idea.

**Comment by mathomp4** [comment]
According to Lyn Gerner, the SLURM limit is 1024 and NAS says PBS is 230. So I suppose, say, 200 characters might be a good limit.

**Comment by mathomp4** [comment]
Ah. `gcmpost.script` (and `gcmclim.script`, `gcmpost_CPLFCSTfull.script`, and `gcmpost_CPLFCSTpart.script`) has something:
```
 240   │ # Determine Number of Nodes if running in BATCH
 241   │ # ---------------------------------------------
 242   │ if( $NCPUS == "NULL"  ) then
 243   │   if ($?PBS_NODEFILE & $?BATCHNAME) then
 244   │      set BATCHJOB  = `qstat | grep $BATCHNAME | grep $LOGNAME | cut -d' ' -f1`
 245   │      set  numjobs  = $#BATCHJOB
 246   │      if( $numjobs != 0 ) then
 247   │         set  NCPUS = `cat $PBS_NODEFILE | wc -l`
 248   │      endif
 249   │   endif
 250   │ endif
 251   │ echo Use: NCPUS = $NCPUS
```
as does a file in mom5 (which we don't care about probably):
```
Components/@GEOSgcm_GridComp/GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/MOM_GEOS5PlugMod/@mom/test/test_bit_reproducibility.py
72:                qsub_out = subprocess.check_output(['qstat', run_id])
```
and `Shared/@GMAO_Shared/GMAO_etc/jobIDfilter` also has a `qstat` reference

I think I know how to untangle the first gcmpost one which is probably the only one that matters. I know how to figure out if I'm batch or not in SLURM. I'll need to figure out a similar one for PBS.

**Comment by lltakacs** [comment]
I have no problem with the longer names in principle.  We would just have to see if any scripts fail due to the longer name.
Larry
