### ISSUE TITLE
gcm_setup broken on macOS

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GEOSgcm_App#17]
Another in a long line of "macOS is BSD and you never forget it". macOS does not have a `readlink` like Linux so this:
https://github.com/GEOS-ESM/GEOSgcm_App/blob/4feefe35539e8f1d4aec3b3d98fe0032c32f1623/gcm_setup#L36
will fail. And since that's line 36, a lot doesn't work after that.

**Comment by mathomp4** [comment]
Query for @tclune: I have a fix for this, should it be a hotfix onto `master` and then folded into `develop`? Seems the correct git way, right?

**Comment by mathomp4** [comment]
The solution, by the way (in case @atrayano needs to do it), is to do this:
```tcsh
setenv ARCH `uname -s`
if ($ARCH == Darwin) then
   set FINDPATH = realpath
else
   set FINDPATH = 'readlink -f'
endif
set GCMSETUP = `$FINDPATH $0`
```
instead.

**Comment by tclune** [comment]
Do we even need to follow the links explicitly?   Isn't the OS supposed to do this for us?   Or do you need to extract the parent directory to "find" associated artifacts?

**Comment by mathomp4** [comment]
All readlink/realpath does is give you the exact path to a file. If it's a symlink it'll also give you the "real" path to that, but I'm using it only for it's purpose of "where is this file". It's the utility I've always used.

I then use that information to figure out where the `install/bin` directory is (using `dirname`). I can then check to make sure `GEOSgcm.x` is in that directory as well. If not, die because you are installing from `Applications/@GEOSgcm_App`.

There might be better ways of doing this, perhaps by making gcm_setup in the `src` tree non-executable and putting the executable bit on during install?

**Comment by tclune** [comment]
OK - I think I understand.     We allow people to run the script as a symlink to the install directory.  You then need to follow the symlink back to find related executables and such.   (I think the point about the executable bit in src is a side issue.)   

I'm still not certain what it is Arlindo is advocating on this front, but I'm guessing that it is either not using a symlink in the first place, _or_ there is a mechanism within a file to find its own path regardless of how it was symlinked.   Which is indeed what you have done now that I've explained it to myself.  :-)
