### ISSUE TITLE
Coupled model cannot run under MPT

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GEOSgcm_App#179]
A warning for @yvikhlya and @sanAkel (as well as pinging @tclune)

Testing has shown that the `LD_PRELOAD` mechanism does not work under MPT. At NCCS you get:
```
/usr/local/sgi/mpi/mpt-2.17/bin/mpiexec_mpt  -np 360 ./GEOSgcm.x --logging_config logging.yaml
srun: cluster configuration lacks support for cpu binding
srun: Warning: can't honor --ntasks-per-node set to 28 which doesn't match the requested tasks 360 with the number of requested nodes 13. Ignoring --ntasks-per-node.
ctrl_vsend/writev failed: Bad file descriptor
srun: error: borgo131: task 306: Broken pipe
srun: error: borgo083: task 56: Broken pipe
srun: error: borgo086: task 140: Broken pipe
srun: error: borgo085: task 112: Broken pipe
srun: error: borgo130: task 279: Broken pipe
srun: error: borgo129: task 252: Broken pipe
srun: error: borgo090: task 224: Broken pipe
srun: error: borgo084: task 84: Broken pipe
srun: error: borgo089: task 196: Broken pipe
srun: error: borgo132: task 333: Broken pipe
srun: error: borgo087: task 168: Broken pipe
srun: error: borgo077: task 28: Broken pipe
srun: error: borgo076: task 0: Exited with exit code 255
```
and things sort of halt.

At NAS the model actually locks up a *LOT* and even the NAS Control Room can not remove the PBS allocation of the job.

I'm going to consult with NAS on figuring this out. For now, don't run MOM or MOM6 with MPT.

**Comment by mathomp4** [comment]
For now, I am going to try and build Baselibs and GEOS with HPC-X (Open MPI) and see if that works. If so, we at least have a possible workaround.

**Comment by sanAkel** [comment]
Sorry! I'm confused, does it **not** work at NCCS? 

The stuff breaks at NAS **only**?

**Comment by mathomp4** [comment]
@sanAkel It doesn't work at NCCS or NAS if you use MPT. It just works...less badly at NCCS.

**Comment by mathomp4** [comment]
More updates. I built an HPC-X version of Baselibs at NAS and I can confirm that MOM6 will run with HPC-X. So this does look more and more like an MPT issue. So I suppose a query might be: should we move to HPC-X by default at NAS?

And, it is nice to say, that running with HPC-X at NAS and Intel MPI at NCCS did give the same answer! Now I ran both on Skylake, so I didn't test chipset diffs, but still, good to know.

Well, `fvcore_internal_checkpoint` was the same after a day. I did see that "total age" was different at the end of the run. NCCS:
```
      Total age:   3.7561330911866173E+18 yr kg
```
NAS:
```
      Total age:   3.7561330911866163E+18 yr kg
```
Not sure why...might just be casting a 32-bit real into a 64-bit?

**Comment by sanAkel** [comment]
@mathomp4 thanks a lot for the updates and keeping at it! :)

Indeed `Total age` is just a _huge_ number! I can take care of looking into any diff in the ocean.

Would you recommend using the HPC-X both at NCCS and NAS?

It is timely since I'm beginning to work on new **coarser** grid, of course for MOM6 (not for the _older_ MOM5).

**Comment by mathomp4** [comment]
@sanAkel Well, we'd want to keep Intel MPI at NCCS. The question is what to do at NAS. I suppose to be "good" I should run a series of runs at NAS on the various machines to make sure HPC-X is not (significantly) slower than MPT. But I'll probably need to annoy Bill to do that (as I'd need more SBUs than our SI Team account can provide).

**Comment by sanAkel** [comment]
> @sanAkel Well, we'd want to keep Intel MPI at NCCS. The question is what to do at NAS. I suppose to be "good" I should run a series of runs at NAS on the various machines to make sure HPC-X is not (significantly) slower than MPT. But I'll probably need to annoy Bill to do that (as I'd need more SBUs than our SI Team account can provide).

@mathomp4 did you happen to get any SBUs from Bill?

**Comment by wmputman** [comment]
@mathomp4 : has there been a resolution to this? @yvikhlya is having issues with the coupled model now.

**Comment by mathomp4** [comment]
@wmputman The solution at present would be to run with HPC-X at NAS, I suppose. The other thought was that the DSO work in https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/377 might also let us avoid the `LD_PRELOAD` not working with MPT issue.

**Comment by yvikhlya** [comment]
@mathomp4 To clarify this, I am trying to move my coupled run to NAS and it does not run there. It just hangs on mpiexec_mpt command.

**Comment by mathomp4** [comment]
@yvikhlya Can you try to replace your `g5_modules` with:
```
/home3/mathomp4/GitG5Modules/SLES12/6.0.27/g5_modules.intel1913.hpcx240
```
at NAS? You'll need to rebuild from scratch, but the last time I tested it worked. (Though that was a while ago.)

**Comment by sanAkel** [comment]
> @wmputman The solution at present would be to run with HPC-X at NAS, I suppose. The other thought was that the DSO work in [GEOS-ESM/GEOSgcm_GridComp#377](https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/377) might also let us avoid the `LD_PRELOAD` not working with MPT issue.

@mathomp4 Please see https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/377#issuecomment-780089433

`LD_PRELOAD` (still) does not work!

**Comment by yvikhlya** [comment]
> @yvikhlya Can you try to replace your `g5_modules` with:
> 
> ```
> /home3/mathomp4/GitG5Modules/SLES12/6.0.27/g5_modules.intel1913.hpcx240
> ```
> 
> at NAS? You'll need to rebuild from scratch, but the last time I tested it worked. (Though that was a while ago.)

Ok, I'll try.

**Comment by yvikhlya** [comment]
> @yvikhlya Can you try to replace your `g5_modules` with:
> 
> ```
> /home3/mathomp4/GitG5Modules/SLES12/6.0.27/g5_modules.intel1913.hpcx240
> ```
> 
> at NAS? You'll need to rebuild from scratch, but the last time I tested it worked. (Though that was a while ago.)

Should I still use `mpiexec_mpt` for run command in this case?

**Comment by mathomp4** [comment]
@yvikhlya No. You'd want to use `mpirun` but `esma_mpirun` will correctly determine the MPI stack.

**Comment by mathomp4** [comment]
@yvikhlya I'm also going to test using Intel MPI at NAS as well. Let me do some tests myself and I'll see if it works with MOM6 as well.

**Comment by sanAkel** [comment]
> @yvikhlya I'm also going to test using Intel MPI at NAS as well. Let me do some tests myself and I'll see if it works with MOM6 as well.

Thank you @mathomp4 

I can report on behalf of @yvikhlya that right now he is trying to run with **MOM5** in a `dual ocean` with flag: `DUAL_OCEAN: 1` in `AGCM.rc` So I would say it would _suffice_ for now if MOM5 works, for you, without, that flag `on.`

**Comment by mathomp4** [comment]
@sanAkel I'll try my usual MOM5/MOM6 runs which I have a script to set up for me easily. If one passes that, then I'll try this fancy new thing! 😄

**Comment by sanAkel** [comment]
@mathomp4 sounds good 👍 

>I'll try this fancy new thing! 

You mean turn on `dual ocean`? You need some files to be in place for it to run, recall:
-  https://github.com/GEOS-ESM/GEOSgcm_GridComp/issues/394
- https://github.com/GEOS-ESM/GEOSgcm/issues/244

**Comment by mathomp4** [comment]
> @mathomp4 sounds good 👍
> 
> > I'll try this fancy new thing!
> 
> You mean turn on `dual ocean`? You need some files to be in place for it to run, recall:
> 
> * [GEOS-ESM/GEOSgcm_GridComp#394](https://github.com/GEOS-ESM/GEOSgcm_GridComp/issues/394)
> * [GEOS-ESM/GEOSgcm#244](https://github.com/GEOS-ESM/GEOSgcm/issues/244)

Oh. Maybe I'll let @yvikhlya do that. Rely on experts, I always say 😄

**Comment by yvikhlya** [comment]
> > @mathomp4 sounds good 👍
> > > I'll try this fancy new thing!
> > 
> > 
> > You mean turn on `dual ocean`? You need some files to be in place for it to run, recall:
> > 
> > * [GEOS-ESM/GEOSgcm_GridComp#394](https://github.com/GEOS-ESM/GEOSgcm_GridComp/issues/394)
> > * [GEOS-ESM/GEOSgcm#244](https://github.com/GEOS-ESM/GEOSgcm/issues/244)
> 
> Oh. Maybe I'll let @yvikhlya do that. Rely on experts, I always say 😄

Yes, I am busy with this right now. Free coupled model runs at NAS with custom g5_modules, but dual ocean starts to run and crashes with segfault in history init. This is unlikely to be related to mpt problem.

**Comment by mathomp4** [comment]
Running with changes to:

1. FMS (https://github.com/GEOS-ESM/GEOSgcm/pull/254)
2. MAPL (https://github.com/GEOS-ESM/MAPL/pull/701)
3. GEOSgcm_GridComp (https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/377)
4. GEOSgcm_App (https://github.com/GEOS-ESM/GEOSgcm_App/pull/204)

I was able to run MOM5 and MOM6 at NAS with MPT.

**Comment by yvikhlya** [comment]
@mathomp4 The run with MOM5 which I was able to run yesterday at NAS, crashes today with
```
libibcm: couldn't read ABI version

```

Any idea what could be a problem?

**Comment by mathomp4** [comment]
Huh. That's a weird one. Is it reproducible? I know libibcm is an Infiniband library but...hmm.

**Comment by sanAkel** [comment]
@yvikhlya:
1. Were you able to reproduce the same issue, yourself? at NAS
2. Irrespective of the slow queue, please keep an _active_ run at NCCS. Thanks!

**Comment by yvikhlya** [comment]
> @yvikhlya:
> 
>     1. Were you able to reproduce the same issue, yourself? at NAS
> 
>     2. Irrespective of the slow queue, please keep an _active_ run at NCCS. Thanks!
> 
> 
> If ⤴️ 1 isn't reproducible, since anyway `LD_PRELOAD` is going away, you could try a new clone with [GEOS-ESM/GEOSgcm_GridComp#377 (comment)](https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/377#issuecomment-781532031) @mathomp4 already checked it works without `dual_ocean`

This issue happens now and then at NAS. When I resubmit the job, it continues running. I continue the run at NCCS and it goes little faster now. I don't want to switch to DSO in the middle of the run, because this will only add confusion. Next run we plan, I'll do with DSO.

**Comment by sanAkel** [comment]
Okay, Thanks @yvikhlya 

In that case seems this issue can be closed because:

- @mathomp4 said above (https://github.com/GEOS-ESM/GEOSgcm_App/issues/179#issuecomment-781449981):
>I was able to run MOM5 and MOM6 at NAS with MPT.

- and @yvikhlya is confirming that coupled model runs at NAS.

Updating @wmputman: things are running!

**Comment by mathomp4** [comment]
All, this might have to reopen. We brought back `LD_PRELOAD` and I think this breaks MOM6 at NAS again. At least, my nightly tests (which I just restarted after all the GOCART2G stuff was fixed at NAS), just time out trying to run MOM6.
