### ISSUE TITLE
MOM6 binarytile.x errors in gcm_run.j

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GEOSgcm_App#180]
If I run MOM6 GEOS (standard C90), you always get this:
```
/gpfsm/dswdev/mathomp4/Models/GEOSgcm-Intel1912/GEOSgcm/install-Release/bin/binarytile.x tile_hist.data tile_hist.bin
forrtl: No such file or directory
forrtl: severe (29): file not found, unit 7, file /gpfsm/dnb02/mathomp4/Experiments/stock-gcm-2020Nov09-1day-c90-MOM6/scratch/tile_hist.data
Image              PC                Routine            Line        Source
binarytile.x       0000000000405BDB  Unknown               Unknown  Unknown
binarytile.x       0000000000415D90  Unknown               Unknown  Unknown
binarytile.x       0000000000402BC3  MAIN__                     25  binarytile.F90
binarytile.x       0000000000402A52  Unknown               Unknown  Unknown
libc-2.22.so       00002AAAAB40D725  __libc_start_main     Unknown  Unknown
binarytile.x       0000000000402969  Unknown               Unknown  Unknown
```
I think the issue is that the run in `scratch/` has a broken symlink for `tile_hist.data`. It's trying to link (on discover):
```
/discover/nobackup/yvikhlia/coupled/Forcings/MOM6/DE0360xPC0181_TM0360xTM0210/DE0360xPC0181_TM0360xTM0210-Pfafstetter.til
```
but that file does not exist. 

Now the model runs so I guess `tile_hist.bin` isn't necessary...but still.

**Comment by yvikhlya** [comment]
Oh yes, I have this error too. I'll fix this.

**Comment by sanAkel** [comment]
@mathomp4 , I hit this issue yesterday while testing your `flush()` PR https://github.com/GEOS-ESM/GEOSgcm/pull/222

I would let @yvikhlya take a crack at this!

@yvikhlya unrelated to this, but we should be having `ocn2d` collections in MOM6 HISTORY, we can chat about it _offline_!

**Comment by sanAkel** [comment]
> Oh yes, I have this error too. I'll fix this.

👍

**Comment by yvikhlya** [comment]
It has to be DC, not DE.

**Comment by sanAkel** [comment]
@mathomp4 with @yvikhlya 's help, it should be:
bin/ln -s /discover/nobackup/yvikhlia/coupled/Forcings/MOM6/DC0360xPC0181_TM0360xTM0210/DC0360xPC0181_TM0360xTM0210-Pfafstetter.til tile_hist.data

I can confirm that with above:
1. The error you reported disappears. 
2. Can output 2d ocean collections, eg., `geosgcm_ocn2d`

**Comment by mathomp4** [comment]
Ahhhh! That's why it didn't matter, I wasn't using an Ocean HISTORY when I tested! I should be choosing `HISTORY.AOGCM.rc.tmpl` when I make a MOM6 run?

**Comment by mathomp4** [comment]
I still might be missing something. I just took the patch from @yvikhlya and the binarytile error is gone, but when I try to use `HISTORY.AOGCM.rc.tmpl` it crashes:
```
 Cannot Find MOM
pe=00000 FAIL at line=01398    MAPL_HistoryGridComp.F90                 <needs informative message>
```
I think because I'm using MOM6 so `MOM` is not a valid component. Is there some sed/awk we should do to fix this? Or maybe use something a la `DYN` so we can extract variables from any ocean model?

**Comment by yvikhlya** [comment]
@mathomp4 You can't use HISTORY.AOGCM.rc.tmpl with MOM6. We need to add another template HISTORY.AOGCM-MOM6.rc.tmpl

**Comment by mathomp4** [comment]
Ahh. I'm dumb. I'll work fixing up my scripts.
