### ISSUE TITLE
Tile file(s) with MOM6 ocean model

### ISSUE THREAD

**Issue by sanAkel** [GEOS-ESM/GEOSgcm_App#219]
Appreciate the creation of tile files for coupled model with MOM6 ocean model. 
For following `ocean (res_ocn) x atmosphere (res_atm)`:

| Availability of ocean grids | Nominal resolution | ocean `IM x JM` | atmosphere cube | _Intended_ purpose |
| :---: | :---: | :--- | :--- | :--- |
| ✔️  | 5-deg | 72 x 36 | c12 | PR testing, debugging, _no_ _science_! |
| ✔️  | 1-deg | 360 x 200 | c90 | climate runs at _low_ resolution |
| ✔️  | 0.25-deg | 1440 x 1080 | c180 | TBD: (_science_, _production_, ...?)  |

The ocean grids are located in following path:
- **5-deg**: ~~`/discover/nobackup/sakella/MOM6-GFDL/Grids/Jun2021/5deg/`~~ `/discover/nobackup/sakella/MOM6-GFDL/Grids/MOM6-grids/5deg/workDir/`
- **1-deg**: `/discover/nobackup/sakella/MOM6-GFDL/Grids/Jun2021/1deg/`
- **0.25-deg**: `/discover/nobackup/sakella/MOM6-GFDL/MOM6-testing/Alistair.Adcroft/OM4_025/mosaic.v20170622.unpacked/`

**Comment by tclune** [comment]
Adding @bena-nasa and @atrayano.    Please add this task to your backlog.   (I fear I might start needing you to maintain a written backlog so that we can juggle priorities over time ...)

**Comment by sanAkel** [comment]
From @zhaobin74 sea ice related files:
```
/gpfsm/dnb31/bzhao/fixed_grid_cice_new/MOM6/grid_cice.bin

/gpfsm/dnb31/bzhao/fixed_grid_cice_new/MOM6/kmt_cice.bin

There are 0 area/length cells in this grid, and 
they are set to a small value to avoid crash in cice transport routine
```
and from @yvikhlya for `MAPL_Tripolar.nc`
`/home/yvikhlia/nobackup/coupled/Forcings/MOM6/OM4_025/MAPL_Tripolar.nc`

**Comment by mathomp4** [comment]
C24x5-deg would be great for testing and debugging purposes!

**Comment by jkrasting** [comment]
> C24x5-deg would be great for testing and debugging purposes!

I second this!

**Comment by yvikhlya** [comment]
Locations for coupled boundary conditions:
```
/discover/nobackup/projects/gmao/ssd/aogcm/ocean_bcs
/discover/nobackup/projects/gmao/ssd/aogcm/atmosphere_bcs
```
