### ISSUE TITLE
Incorporate default-run-type-safe updates from L132 work

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GEOSgcm_App#23]
Per the branch `feature/wmputman/FV3nh_GFDLmp_L132` created by @wmputman, there are some possible changes in the pull request #22 that could be useful and safe for the default L72-1Moment runs of GEOS. 

Unfortunately, that pull would put everyone in NH/GFDL land. But, possibly the edits to `fvcore_layout.rc` are needed? And the changes in `gcm_forecast.tmpl` HISTORY look safe?

**Comment by wmputman** [comment]
gcm_forecast.tmpl changes to HISTORY are fine, the fvcore_layout.rc should not be pulled into the main development branch yet
