### ISSUE TITLE
land options seperate from AGCM.rc desired

### ISSUE THREAD

**Issue by JustinPerket** [GEOS-ESM/GEOSgcm_App#30]
@smahanam has code in cvs that takes catch and catchCN-related options out of AGM.rc and into a dedicated land resource file. Previous objections about duplication of LDAS.rc are now moot since LDAS.rc is now in the GEOSldas repo. It would be trivial to implement.

**Comment by tclune** [comment]
@ehackert  Does UMD _need_ its own AGCM.rc file, or is this a development artifact that could be cleaned up?

**Comment by JustinPerket** [comment]
@smahanam 

GEOS_LandGridComp.rc in https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/61/files should be put in it's own pull request.

This Pull Request is also needed, https://github.com/GEOS-ESM/GEOSgcm_App/pull/39, which looks good except for the issues raised there
