### ISSUE TITLE
Aerosol updates

### ISSUE THREAD

**Issue by adarmenov** [GEOS-ESM/GEOSgcm_App#51]
The default GOCART configuration was modified to enable brown carbon (BrC). HISTORY.AGCM.rc.tmpl and HISTORY.rc.tmpl need to be extended to include the additional BrC diagnostics. 

GOCART is coupled with ACHEM, which means that ACHEM will be actively used in the foreseeable future. I renamed the ACHEM restart files to make them more consistent with the restarts naming scheme. This is a good time to make this change before ACHEM restarts become (more) commonly used.

**Comment by mathomp4** [comment]
Closing as I think GOCART2G now does all this
