### ISSUE TITLE
linkbcs issue for coupled runs with v12 bcs 

### ISSUE THREAD

**Issue by biljanaorescanin** [GEOS-ESM/GEOSgcm_App#622]
During GCM coupled run, linkbcs.tmpl will try to search for the file `MAPL_Tripolar.nc` in bcs geometry dir. 

In linkbcs.tmpl :
`/bin/ln -sf $BCSDIR/geometry/${BCRSLV}/MAPL_Tripolar.nc`

But this file is part of  **ocean inputs**:
`/discover/nobackup/projects/gmao/bcs_shared/make_bcs_inputs/ocean/MOM6/`

To fix code for now I've copied MAPL_Tripolar.nc to geometry dir of v12 but do we need to change this or not? 

This issue was found by @zhaobin74 during MOM6 v12 testing.

**Comment by zhaobin74** [comment]
Thanks, @biljanaorescanin for opening this issue.
This file, ```MAPL_Tripolar.nc```, is historically part of the ocean BC and independent of land BC. So it is better to directly link from ocean BC location (```CPLDIR``` in ```linkbcs.tmpl```) instead of saving another copy in ```BCSDIR``` and link from there.

**Comment by mathomp4** [comment]
@biljanaorescanin @zhaobin74 Once you all figure out where this should go, either myself or @sshakoor1 can update the scripts if needed.

**Comment by biljanaorescanin** [comment]
This is where they should be read from : 
`/discover/nobackup/projects/gmao/bcs_shared/make_bcs_inputs/ocean/ and than MOM5 or MOM6 and than diff ogrid`
