### ISSUE TITLE
Add ability to select node type in gcm_setup

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GEOSgcm_App#96]
With the fact that NCCS will soon have a mixed Haswell-Skylake environment, we need a way to make it easy for the end-user to select which one they want. A question (and accompanying code) should be added to `gcm_setup` so that (at least) `gcm_run.j` is correctly transformed.

And, of course, it should handle all of the NAS types as well.

**Comment by mathomp4** [comment]
Okay. I think I have a good shot at this, but I might need @mmanyin to weigh in on it before I make a PR. I have a branch:
```
feature/mathomp4/add-model-question
```
that seems to work for me.

But, I'd like @mmanyin to test with GMI. The reason is that `gmichem_setup` did some changes to `--ntasks-per-node` for SLURM, using 27 instead of 28 on Haswell at NCCS.

So, in my branch's `gmichem_setup` I take whichever processor type you select and then subtract one from it. Maybe not perfect, but I want the Haswell experience to be the same.

**Comment by mmanyin** [comment]
That's a good approach for now, thanks for including it!
